# -*- coding: utf-8 -*-
"""projeto-algoritmo-de-auditoria-de-dados.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eplEldd9C5eJs4JkzaigFXi-v8cKc5RF
"""

# Configuração Global

LIMITE_SEGURANCA = 10000.0



# Entrada de Dados (com casting para float)

venda1 = float(input("Digite o valor da venda 1: "))

venda2 = float(input("Digite o valor da venda 2: "))

venda3 = float(input("Digite o valor da venda 3: "))



def analisar_vendas(v1, v2, v3):

  global LIMITE_SEGURANCA



  # Cálculo da média

  media = (v1 + v2 + v3) / 3



  print(f"\nMédia das vendas: R$ {media:.2f}")



  # Lógica de investigação

  if media > LIMITE_SEGURANCA:

    print("⚠️ SISTEMA EM QUARENTENA")



  # Verificar discrepância (5x maior que a média)

  for venda in [v1, v2, v3]:

    if venda > media * 5:

      print("🔎 REVISÃO MANUAL NECESSÁRIA")



  # Possibilidade de alterar limite

  for venda in [v1, v2, v3]:

    if venda > LIMITE_SEGURANCA:

      resposta = input("Venda alta detectada. Deseja atualizar o LIMITE_SEGURANCA? (s/n): ")

      if resposta.lower() == 's':

        novo_limite = float(input("Digite o novo limite: "))

        LIMITE_SEGURANCA = novo_limite

        print(f"Novo LIMITE_SEGURANCA definido: R$ {LIMITE_SEGURANCA:.2f}")



  # Apresentação dos tipos

  print("\n--- Tipos de Dados ---")

  print(f"venda1: {type(v1)}")

  print(f"venda2: {type(v2)}")

  print(f"venda3: {type(v3)}")

  print(f"media: {type(media)}")

  print(f"LIMITE_SEGURANCA: {type(LIMITE_SEGURANCA)}")



# Executar análise

analisar_vendas(venda1, venda2, venda3)