# -*- coding: utf-8 -*-
"""Desafio_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1siHwa3CnaU2gmFQefVKVbV69_xQRYQ8l
"""

# Estrutura:

#   dicionário  →  playlist com metadados e álbuns

#   lista       →  sequência de álbuns (mutável, reordenável)

#   tupla       →  metadados fixos de cada frame (imutáveis)



playlist = {

    "titulo": "Minha Playlist Visual",

    "versao": (1, 0, 0),          # tupla imutável (major, minor, patch)

    "albuns": [                     # lista de álbuns (mutável)

        {

            "nome": "Emoções",

            "frames": [

                ("😀", "Feliz",    (255,255,0)),   # tupla: (emoji, rótulo, cor dominante)

                ("😢", "Triste",   (100,149,237)),

                ("😡", "Raiva",    (220,50,50)),

            ]

        },

        {

            "nome": "Natureza",

            "frames": [

                ("🌳", "Árvore",   (34,139,34)),

                ("🌊", "Onda",     (0,105,148)),

            ]

        },

    ]

}



# ── Operações obrigatórias ────────────────────────────────────────



# .pop() — remove o último álbum da lista

album_removido = playlist["albuns"].pop()

print(f"Álbum removido: {album_removido['nome']}")



# .insert() — reinsere no início da lista

playlist["albuns"].insert(0, album_removido)

print("Álbuns após reordenação:",

      [a["nome"] for a in playlist["albuns"]])



# ── 3 níveis de FOR ──────────────────────────────────────────────

print(f"\nPlaylist: {playlist['titulo']} v{playlist['versao']}\n")



# NÍVEL 1 — percorre as chaves do dicionário raiz

for chave in playlist.keys():

    if chave == "albuns":



        # NÍVEL 2 — percorre cada álbum (dicionário) dentro da lista

        for album in playlist["albuns"]:

            print(f"  Álbum: {album['nome']}")



            # NÍVEL 3 — percorre cada frame (tupla) dentro do álbum

            for emoji, rotulo, (r, g, b) in album["frames"]:

                # Desempacotamento de tupla aninhada direto no for

                print(f"    {emoji} {rotulo:<10} RGB({r},{g},{b})")