# -*- coding: utf-8 -*-
"""desafio_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XzlCoSgKrdj4jzeP2VoGbAcNMI6hm2Qw
"""

emoji_data = {

    "nome": "Smile",

    "grade": [

        [(255,255,0), (255,255,0), (255,255,0), (255,255,0), (255,255,0)],

        [(255,255,0), (0,0,0),     (255,255,0), (0,0,0),     (255,255,0)],

        [(255,255,0), (255,255,0), (255,255,0), (255,255,0), (255,255,0)],

        [(255,255,0), (0,0,0),     (0,0,0),     (0,0,0),     (255,255,0)],

        [(255,255,0), (255,255,0), (255,255,0), (255,255,0), (255,255,0)],

    ]

}



AMARELO = (255, 255, 0)

nova_grade = []



# NÍVEL 1 — percorre pares chave/valor do dicionário

for chave, valor in emoji_data.items():

    if chave == "grade":



        # NÍVEL 2 — percorre cada linha da grade

        for linha in valor:

            nova_linha = []



            # NÍVEL 3 — percorre cada pixel (tupla R,G,B) da linha

            for pixel in linha:

                if pixel == AMARELO:

                    # Tuplas são imutáveis → criamos uma NOVA tupla com 50% de brilho

                    pixel_sombra = (pixel[0] // 2,

                                    pixel[1] // 2,

                                    pixel[2] // 2)

                    nova_linha.append(pixel_sombra)

                else:

                    # Pixels pretos (olhos/boca) não são alterados

                    nova_linha.append(pixel)



            nova_grade.append(nova_linha)



emoji_data["grade"] = nova_grade



# Resultado esperado (amarelo escurecido = (127,127,0), preto = (0,0,0)):

for linha in emoji_data["grade"]:

    print(linha)