# -*- coding: utf-8 -*-
"""algoritmo_microclima_local.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-UUnMderZCSyPDHM0TMdiqYHLsBYWAHK
"""

def analisar_dados():



  # Lista de listas: [local, temperatura, umidade, IQA]

  dados_locais = [

    ["Terminal Cidade Tiradentes", 20, 85, 42],

    ["Corinthians-Itaquera", 22, 74, 75],

    ["Shopping Tatuapé", 23, 70, 68],

    ["Terminal Cidade Tiradentes", 26, 60, 58],

    ["Corinthians-Itaquera", 29, 50, 110],

    ["Shopping Tatuapé", 30, 48, 95]

  ]



  print("=== ANÁLISE DOS DADOS ===\n")



  # Loop principal (locais)

  for local in dados_locais:

    nome = local[0]



    print(f"Local: {nome}")



    # Loop interno (métricas)

    for i in range(1, len(local)):

      if i == 1:

        print(f"Temperatura: {local[i]}°C")

      elif i == 2:

        print(f"Umidade: {local[i]}%")

      elif i == 3:

        print(f"IQA: {local[i]}")



    iqa = local[3]



    # Classificação com match-case (base oficial CETESB)

    match True:

      case _ if iqa <= 40:

        classificacao = "Boa"

      case _ if iqa <= 80:

        classificacao = "Moderada"

      case _ if iqa <= 120:

        classificacao = "Ruim"

      case _ if iqa <= 200:

        classificacao = "Muito Ruim"

      case _:

        classificacao = "Péssima"



    print(f"Classificação do Ar: {classificacao}")



    # Fórmula da Nota de Conforto Urbano (0 a 10)

    temperatura = local[1]

    umidade = local[2]



    # Penalização de extremos

    penal_temp = abs(25 - temperatura) * 0.2

    penal_umidade = abs(60 - umidade) * 0.05

    penal_iqa = iqa * 0.03



    nota = 10 - (penal_temp + penal_umidade + penal_iqa)



    # Limitar entre 0 e 10

    if nota < 0:

      nota = 0

    elif nota > 10:

      nota = 10



    print(f"Nota de Conforto Urbano: {nota:.2f}\n")





# Função principal

analisar_dados()