# -*- coding: utf-8 -*-
"""navegação_evacuação_espacial.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ULpf5BofX4uVoFIY1m0lzApFQQSFd5UZ
"""

def simulador_evacuacao():



  # Lista de locais (nós do trajeto)

  locais = [

    "Seu Quarto",

    "Outro Quarto",

    "Escada",

    "Sala",

    "Cozinha",

    "Saída"

  ]



  # Estado de cada local (obstáculos/facilitadores)

  estados = [

    "caminho livre",

    "chave disponível",

    "escada estreita",

    "porta trancada",

    "fogo leve",

    "saida"

  ]



  # Inventário

  tem_chave = False



  # Controle

  posicao = 0

  energia = 10



  print("=== SIMULAÇÃO DE EVACUAÇÃO ===\n")



  while energia > 0:



    local_atual = locais[posicao]

    estado_atual = estados[posicao]



    print(f"Você está em: {local_atual}")

    print(f"Situação: {estado_atual}")



    # Condições

    if estado_atual == "saida":

      print("Você saiu da casa com sucesso!")

      break



    elif estado_atual == "caminho livre":

      posicao += 1



    elif estado_atual == "chave disponível":

      print("Você encontrou uma chave!")

      tem_chave = True

      posicao += 1



    elif estado_atual == "escada estreita":

      if energia > 1:

        print("Você desceu a escada com cuidado.")

        energia -= 1

        posicao += 1

      else:

        print("Sem energia para descer! Voltando...")

        posicao -= 1



    elif estado_atual == "porta trancada":

      if tem_chave:

        print("Você abriu a porta da sala com a chave.")

        posicao += 1

      else:

        print("Porta trancada! Você precisa de uma chave. Voltando...")

        posicao -= 1



    elif estado_atual == "fogo leve":

      if energia > 3:

        print("Você atravessou a cozinha com fogo!")

        energia -= 3

        posicao += 1

      else:

        print("Sem energia para atravessar o fogo! Voltando...")

        posicao -= 1



    else:

      print("Situação desconhecida. Voltando...")

      posicao -= 1



    # Evitar sair da lista

    if posicao < 0:

      posicao = 0



    energia -= 1

    print(f"Energia restante: {energia}\n")



  if energia <= 0:

    print("Você não conseguiu sair. Ficou sem energia.")





# Executar

simulador_evacuacao()