# -*- coding: utf-8 -*-
"""analisar_clima.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GicAdYoHjdSvi_UWCL_fI7HUO0tfU7vi
"""

def analisar_clima():

  soma_temperaturas = 0.0

  dias_quentes = 0

  alerta_extremo = False



  for dia in range(1, 8):

    temp = float(input(f"Digite a temperatura do dia {dia}: "))

    soma_temperaturas += temp



    if temp > 35.0:

      dias_quentes += 1



    if temp > 45.0 or temp < -5.0:

      alerta_extremo = True



  media = soma_temperaturas / 7



  print(f"Média semanal: {media:.2f}")

  print(f"Dias acima de 35°C: {dias_quentes}")



  if alerta_extremo:

    print("CUIDADO: Condições climáticas perigosas detectadas!")

  else:

    print("Clima dentro da normalidade operacional.")