# -*- coding: utf-8 -*-
"""sistemas_notas_turma.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u_blJUQsmGvjJMgcrlXeNHlJRZext7pS
"""

def sistema_notas_turma():

  total_alunos = int(input("Quantos alunos existem na turma? "))



  for j in range(1, total_alunos + 1):

    aluno_nome = input("Nome do aluno: ")

    n1 = float(input("Nota 1: "))

    n2 = float(input("Nota 2: "))



    media_aluno = (n1 + n2) / 2



    if media_aluno >= 7.0:

      print(f"{aluno_nome}: Aprovado com média {media_aluno:.2f}")

    elif media_aluno >= 5.0:

      print(f"{aluno_nome}: Recuperação (Média: {media_aluno:.2f})")

    else:

      print(f"{aluno_nome}: Reprovado")